spring:
  application:
    name: minio-storage
  datasource:
    url: "jdbc:mysql://localhost:3300/minio_storage_service"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  mail:
#    host: "smtp.gmail.com"
#    port: 587
#    username: "quangthinh06112004@gmail.com"
#    password: "xpwa adnf fucb tkzk"
#    properties:
#      mail:
#        smtp:
#          auth: true
#        starttls:
#          enable: true
server:
  port: 8080
  servlet:
    context-path: /minio


integration:
  minio:
    access-key: admin
    secret-key: admin@2024
    url: http://localhost:9000

#redis:
#  host: redis-container
#  port: 6379
redis:
  host: localhost
  port: 6379




